# Generated by Django 5.2.5 on 2025-09-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
